name: Automated Geyser and SDKMAN! Deployment
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  deploy:
    name: Automated Geyser and SDKMAN! Deployment
    runs-on: [self-hosted, Linux, X64, ansible]
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Ansible Galaxy Roles 
        run: ansible-galaxy install -r requirements.yml --force
      - name: Decrypt Ansible Vault
        run: echo $ANSIBLE_VAULT_PASSWORD > .vault_password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      - name: Add ssh key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Ansible version
        run: ansible --version
      - name: Run Bedrock Playbook
        run: ansible-playbook -i inventory-vault.yml bedrock.yml --private-key private_key.pem --check
