name: Dry Run Ansible Playbook Bedrock

on:
  pull_request:
    paths:
      - 'bedrock.yml'
      - 'bedrock/**'

jobs:
  dry-run:
    name: Dry Run Ansible Playbook Bedrock
    runs-on: [self-hosted, Linux, X64, ansible]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Ansible Galaxy Roles
        run: ansible-galaxy install -r requirements.yml --force
      - name: Decrypt Ansible Vault
        run: echo $ANSIBLE_VAULT_PASSWORD > .vault_password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      - name: Add ssh key
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Ansible version
        run: ansible --version
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory-vault.yml bedrock.yml --check
