name: Manual Playbook Run

on:
  workflow_dispatch:

jobs:
  run-bedrock:
    name: Run Bedrock Playbook
    runs-on: [self-hosted, Linux, X64, ansible]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible Galaxy Roles
        run: ansible-galaxy install -r requirements.yml --force

      - name: Decrypt Ansible Vault
        run: echo $ANSIBLE_VAULT_PASSWORD > .vault_password
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      - name: Add ssh key
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Run Bedrock Playbook
        run: ansible-playbook -vvv -i inventory-vault.yml bedrock.yml --private_key.pem --check

  # Add additional playbooks as separate jobs
  # Example:
  # run-another-playbook:
  #   name: Run Another Playbook
  #   runs-on: self-hosted
  #
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #
  #     - name: Install Ansible Galaxy Roles
  #       run: ansible-galaxy install -r requirements.yml
  #
  #     - name: Decrypt Ansible Vault
  #       run: echo $ANSIBLE_VAULT_PASSWORD > .vault_password
  #       env:
  #         ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
  #
  #     - name: Run Another Playbook
  #       run: ansible-playbook -i inventory-vault.yml another-playbook.yml --check